### PR TITLE
Add option to use a direct or self-managed webhook

### PR DESCRIPTION
**Pull request by nihalgonsalves**
This PR adds support to optionally directly listen for Webhooks. This requires port-forwarding/dynamic DNS, but cuts out the middleman service.

### CODE REVIEW

**Comment by lukasroegner** [comment]
@nihalgonsalves, thank you so much for your contribution. I already merged two of your three PRs, could you resolve the conflicts on this one?

Another question: Is there an easy way to test your implementation (I cannot use DynDNS and NAT)?

**Comment by nihalgonsalves** [comment]
Thanks!

Yup, not at a computer right now but I can do it in a couple of days.

You can use www.serveo.net to test webhooks.

**Comment by nihalgonsalves** [comment]
@lukasroegner Fixed

**Comment by lukasroegner** [comment]
I'll test your implementation and accept the PR afterwards.

**Comment by nihalgonsalves** [comment]
@lukasroegner just a quick reminder :)

**Comment by lukasroegner** [comment]
Checked you implementation with serveo!

**Pull request merged**
