### PR TITLE
Convert to TypeScript

### PR DESCRIPTION
**Pull request by nihalgonsalves**
BREAKING CHANGES: 

- Drops support for ‘password’ authentication type
- Config overhaul (see README for migration guide)
- alwaysOpenSwitch renamed to dangerouslyEnableAlwaysOpenSwitch

Minor changes:

- Automatically setup default snapshot image for the video doorbell
- Better API rate-limit handling and logging
- Local webhook URLs now have a unique ID
- Webhook URLs are rotated periodically (same interval as the location updates)

Non-feature changes:

- Convert to TypeScript
- Add test server config generation for easy local testing
- Add automatic doc generation for configuration and defaults
- Refactor callbacks to async/await
- Refactor prototype setup to ES6+ class
- Move all API requests into single client
- Deduplicate other code
- Fix stray `Buffer()` call => `Buffer.alloc()`

TODO:

- [x] @lukasroegner Enable GitHub Pages for `/docs`
- [x] Bump `major` version ([here](https://github.com/lukasroegner/homebridge-nello/actions?query=workflow%3Abump-version))
- [x] Publish release

### CODE REVIEW

**Comment by lukasroegner** [comment]
GitHub pages enabled for `/docs`.

**Comment by nihalgonsalves** [comment]
@lukasroegner thanks! you can look at the docs here: https://lukasroegner.github.io/homebridge-nello/ (maybe we could put that into the repo website URL)

Specifically the config documentation here: https://lukasroegner.github.io/homebridge-nello/modules/_config_.html

That's generated from: https://github.com/lukasroegner/homebridge-nello/blob/master/src/config.ts

**Comment by lukasroegner** [comment]
@nihalgonsalves Thanks, that's great!

I noticed that the following link doesn't work: "Nello Public API: see all methods in **APIClient**" in the docs

**Comment by nihalgonsalves** [comment]
Ah, makes sense, it's a relative link and typegen doesn't know what to do with it (though it works from GitHub's interface). Fixed in cca0d19ed0d29853925b96fe6cfeda1c9ac081c1.

I'll create a patch release now to see if everything works correctly.

**Comment by nihalgonsalves** [comment]
Hm, I get this error once I moved it to the other workflow in cca0d19ed0d29853925b96fe6cfeda1c9ac081c1

```
npm ERR! code E404
69
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/homebridge-nello - Not found
70
npm ERR! 404 
71
```

https://github.com/lukasroegner/homebridge-nello/runs/939936500?check_suite_focus=true

Is the secret somehow restricted to only one workflow?

**Comment by lukasroegner** [comment]
I checked that, the NPM Access Token I created is allowed to publish (you only have the option to "read" or "read and publish").

**Comment by nihalgonsalves** [comment]
@lukasroegner My mistake, fixed in 79592810afc429f5ba0859e6798aee5fb611a5c7

See: https://github.com/lukasroegner/homebridge-nello/runs/940208219?check_suite_focus=true

**Pull request merged**
